config_url: "https://sincromisor.example.com/api/v1/RTCSignalingServer/config.json"
# 明示指定が必要な場合のみ利用（config_url指定時は通常不要）
# offer_url: "https://sincromisor.example.com/api/v1/RTCSignalingServer/offer"
# candidate_url: "https://sincromisor.example.com/api/v1/RTCSignalingServer/candidate"
# ice_server: "stun:stun.example.com:3478"
# ice_servers:
#   - urls: ["stun:stun.example.com:3478"]
talk_mode: "sincro"
sender_device:
    channels: 1
    samplerate: 48000
    dtype: "int16"
    blocksize: 960
    device: null
receiver_device:
    channels: 2
    samplerate: 48000
    dtype: "int16"
    blocksize: 960
    device: null
